/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotifyImplicitCallbackRouteImport } from './routes/spotify-implicit-callback'
import { Route as SpotifyDashboardRouteImport } from './routes/spotify-dashboard'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify.callback'
import { Route as SongsIdRouteImport } from './routes/songs.$id'
import { Route as SettingsYoutubeRouteImport } from './routes/settings.youtube'
import { Route as SettingsSpotifyRouteImport } from './routes/settings.spotify'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsHistoryRouteImport } from './routes/settings.history'
import { Route as SettingsAudioRouteImport } from './routes/settings.audio'
import { Route as LibraryDownloadedRouteImport } from './routes/library.downloaded'
import { Route as LibraryIdRouteImport } from './routes/library.$id'
import { Route as ApiAnalyzeMoodRouteImport } from './routes/api/analyze-mood'
import { Route as AuthenticatedSpotifyLibraryRouteImport } from './routes/_authenticated/spotify-library'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicTrackCoverRouteImport } from './routes/api/public/track-cover'
import { Route as ApiPublicArtistImageRouteImport } from './routes/api/public/artist-image'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHealthYoutubeRouteImport } from './routes/api/public/health.youtube'

const SpotifyImplicitCallbackRoute = SpotifyImplicitCallbackRouteImport.update({
  id: '/spotify-implicit-callback',
  path: '/spotify-implicit-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyDashboardRoute = SpotifyDashboardRouteImport.update({
  id: '/spotify-dashboard',
  path: '/spotify-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify/callback',
  path: '/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIdRoute = SongsIdRouteImport.update({
  id: '/songs/$id',
  path: '/songs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsYoutubeRoute = SettingsYoutubeRouteImport.update({
  id: '/settings/youtube',
  path: '/settings/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSpotifyRoute = SettingsSpotifyRouteImport.update({
  id: '/settings/spotify',
  path: '/settings/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHistoryRoute = SettingsHistoryRouteImport.update({
  id: '/settings/history',
  path: '/settings/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAudioRoute = SettingsAudioRouteImport.update({
  id: '/settings/audio',
  path: '/settings/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryDownloadedRoute = LibraryDownloadedRouteImport.update({
  id: '/downloaded',
  path: '/downloaded',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiAnalyzeMoodRoute = ApiAnalyzeMoodRouteImport.update({
  id: '/api/analyze-mood',
  path: '/api/analyze-mood',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpotifyLibraryRoute =
  AuthenticatedSpotifyLibraryRouteImport.update({
    id: '/spotify-library',
    path: '/spotify-library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackCoverRoute = ApiPublicTrackCoverRouteImport.update({
  id: '/api/public/track-cover',
  path: '/api/public/track-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtistImageRoute = ApiPublicArtistImageRouteImport.update({
  id: '/api/public/artist-image',
  path: '/api/public/artist-image',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthYoutubeRoute = ApiPublicHealthYoutubeRouteImport.update({
  id: '/api/public/health/youtube',
  path: '/api/public/health/youtube',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spotify-dashboard': typeof SpotifyDashboardRoute
  '/spotify-implicit-callback': typeof SpotifyImplicitCallbackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/spotify-library': typeof AuthenticatedSpotifyLibraryRoute
  '/api/analyze-mood': typeof ApiAnalyzeMoodRoute
  '/library/$id': typeof LibraryIdRoute
  '/library/downloaded': typeof LibraryDownloadedRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/spotify': typeof SettingsSpotifyRoute
  '/settings/youtube': typeof SettingsYoutubeRoute
  '/songs/$id': typeof SongsIdRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/artist-image': typeof ApiPublicArtistImageRoute
  '/api/public/track-cover': typeof ApiPublicTrackCoverRoute
  '/api/public/health/youtube': typeof ApiPublicHealthYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spotify-dashboard': typeof SpotifyDashboardRoute
  '/spotify-implicit-callback': typeof SpotifyImplicitCallbackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/spotify-library': typeof AuthenticatedSpotifyLibraryRoute
  '/api/analyze-mood': typeof ApiAnalyzeMoodRoute
  '/library/$id': typeof LibraryIdRoute
  '/library/downloaded': typeof LibraryDownloadedRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/spotify': typeof SettingsSpotifyRoute
  '/settings/youtube': typeof SettingsYoutubeRoute
  '/songs/$id': typeof SongsIdRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/artist-image': typeof ApiPublicArtistImageRoute
  '/api/public/track-cover': typeof ApiPublicTrackCoverRoute
  '/api/public/health/youtube': typeof ApiPublicHealthYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spotify-dashboard': typeof SpotifyDashboardRoute
  '/spotify-implicit-callback': typeof SpotifyImplicitCallbackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/spotify-library': typeof AuthenticatedSpotifyLibraryRoute
  '/api/analyze-mood': typeof ApiAnalyzeMoodRoute
  '/library/$id': typeof LibraryIdRoute
  '/library/downloaded': typeof LibraryDownloadedRoute
  '/settings/audio': typeof SettingsAudioRoute
  '/settings/history': typeof SettingsHistoryRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/spotify': typeof SettingsSpotifyRoute
  '/settings/youtube': typeof SettingsYoutubeRoute
  '/songs/$id': typeof SongsIdRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/artist-image': typeof ApiPublicArtistImageRoute
  '/api/public/track-cover': typeof ApiPublicTrackCoverRoute
  '/api/public/health/youtube': typeof ApiPublicHealthYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/spotify-dashboard'
    | '/spotify-implicit-callback'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/spotify-library'
    | '/api/analyze-mood'
    | '/library/$id'
    | '/library/downloaded'
    | '/settings/audio'
    | '/settings/history'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/spotify'
    | '/settings/youtube'
    | '/songs/$id'
    | '/spotify/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/artist-image'
    | '/api/public/track-cover'
    | '/api/public/health/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/spotify-dashboard'
    | '/spotify-implicit-callback'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/spotify-library'
    | '/api/analyze-mood'
    | '/library/$id'
    | '/library/downloaded'
    | '/settings/audio'
    | '/settings/history'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/spotify'
    | '/settings/youtube'
    | '/songs/$id'
    | '/spotify/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/artist-image'
    | '/api/public/track-cover'
    | '/api/public/health/youtube'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/spotify-dashboard'
    | '/spotify-implicit-callback'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/spotify-library'
    | '/api/analyze-mood'
    | '/library/$id'
    | '/library/downloaded'
    | '/settings/audio'
    | '/settings/history'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/spotify'
    | '/settings/youtube'
    | '/songs/$id'
    | '/spotify/callback'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/artist-image'
    | '/api/public/track-cover'
    | '/api/public/health/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpotifyDashboardRoute: typeof SpotifyDashboardRoute
  SpotifyImplicitCallbackRoute: typeof SpotifyImplicitCallbackRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAnalyzeMoodRoute: typeof ApiAnalyzeMoodRoute
  SettingsAudioRoute: typeof SettingsAudioRoute
  SettingsHistoryRoute: typeof SettingsHistoryRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsSpotifyRoute: typeof SettingsSpotifyRoute
  SettingsYoutubeRoute: typeof SettingsYoutubeRoute
  SongsIdRoute: typeof SongsIdRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicArtistImageRoute: typeof ApiPublicArtistImageRoute
  ApiPublicTrackCoverRoute: typeof ApiPublicTrackCoverRoute
  ApiPublicHealthYoutubeRoute: typeof ApiPublicHealthYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotify-implicit-callback': {
      id: '/spotify-implicit-callback'
      path: '/spotify-implicit-callback'
      fullPath: '/spotify-implicit-callback'
      preLoaderRoute: typeof SpotifyImplicitCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify-dashboard': {
      id: '/spotify-dashboard'
      path: '/spotify-dashboard'
      fullPath: '/spotify-dashboard'
      preLoaderRoute: typeof SpotifyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify/callback': {
      id: '/spotify/callback'
      path: '/spotify/callback'
      fullPath: '/spotify/callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$id': {
      id: '/songs/$id'
      path: '/songs/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof SongsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/youtube': {
      id: '/settings/youtube'
      path: '/settings/youtube'
      fullPath: '/settings/youtube'
      preLoaderRoute: typeof SettingsYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/spotify': {
      id: '/settings/spotify'
      path: '/settings/spotify'
      fullPath: '/settings/spotify'
      preLoaderRoute: typeof SettingsSpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/history': {
      id: '/settings/history'
      path: '/settings/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof SettingsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audio': {
      id: '/settings/audio'
      path: '/settings/audio'
      fullPath: '/settings/audio'
      preLoaderRoute: typeof SettingsAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/downloaded': {
      id: '/library/downloaded'
      path: '/downloaded'
      fullPath: '/library/downloaded'
      preLoaderRoute: typeof LibraryDownloadedRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/analyze-mood': {
      id: '/api/analyze-mood'
      path: '/api/analyze-mood'
      fullPath: '/api/analyze-mood'
      preLoaderRoute: typeof ApiAnalyzeMoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/spotify-library': {
      id: '/_authenticated/spotify-library'
      path: '/spotify-library'
      fullPath: '/spotify-library'
      preLoaderRoute: typeof AuthenticatedSpotifyLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-cover': {
      id: '/api/public/track-cover'
      path: '/api/public/track-cover'
      fullPath: '/api/public/track-cover'
      preLoaderRoute: typeof ApiPublicTrackCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/artist-image': {
      id: '/api/public/artist-image'
      path: '/api/public/artist-image'
      fullPath: '/api/public/artist-image'
      preLoaderRoute: typeof ApiPublicArtistImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/youtube': {
      id: '/api/public/health/youtube'
      path: '/api/public/health/youtube'
      fullPath: '/api/public/health/youtube'
      preLoaderRoute: typeof ApiPublicHealthYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSpotifyLibraryRoute: typeof AuthenticatedSpotifyLibraryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSpotifyLibraryRoute: AuthenticatedSpotifyLibraryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LibraryRouteChildren {
  LibraryIdRoute: typeof LibraryIdRoute
  LibraryDownloadedRoute: typeof LibraryDownloadedRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIdRoute: LibraryIdRoute,
  LibraryDownloadedRoute: LibraryDownloadedRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpotifyDashboardRoute: SpotifyDashboardRoute,
  SpotifyImplicitCallbackRoute: SpotifyImplicitCallbackRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAnalyzeMoodRoute: ApiAnalyzeMoodRoute,
  SettingsAudioRoute: SettingsAudioRoute,
  SettingsHistoryRoute: SettingsHistoryRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsSpotifyRoute: SettingsSpotifyRoute,
  SettingsYoutubeRoute: SettingsYoutubeRoute,
  SongsIdRoute: SongsIdRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicArtistImageRoute: ApiPublicArtistImageRoute,
  ApiPublicTrackCoverRoute: ApiPublicTrackCoverRoute,
  ApiPublicHealthYoutubeRoute: ApiPublicHealthYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
